# call me by 'REVIEW_TEMPLATE=review-jlreq REVIEW_CONFIG_FILE=config-jlreq.yml rake pdf'
inherit: ["config.yml"]
# texdocumentclass: ["review-jlreq", "media=print,paper=b5j"]
texdocumentclass: ["review-jlreq", "media=ebook,paper=b5j"]
# texdocumentclass: ["review-jlreq", "media=print,paper=b5j,bleed_margin=3mm,cover=true,Q=14,startpage=3,serial_pagination=true,hiddenfolio=nikko-pc"]
